In [1]:
##1. creating arrays

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]


In [3]:
arr__list1 = np.array(list1)

In [4]:
print(arr__list1)

[1 2 3]


In [7]:
print(type(arr__list1))


<class 'numpy.ndarray'>


In [5]:
list1 = [1,2,3]
list2 = [4,5,6]
arr__list1_2 = np.array([list1,list2])
print(arr__list1_2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr__list1_2.ndim)

2


In [ ]:
##2.numpy array attributes


In [7]:
import numpy as np

In [8]:
arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [9]:
print("shape",arr1.shape)
print("size", arr1.shape)
print("dtype",arr1.dtype)

shape (2, 3)
size (2, 3)
dtype int64


In [10]:
##creating 2 arra-1d and 3d ,and findind it's attribute

In [11]:
arr1 = np.array([10,20,30,40,50])
arr3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print("1-D Array:")
print(arr1)
print("\n3-D Array:")
print(arr3)

1-D Array:
[10 20 30 40 50]

3-D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print("shape",arr1.shape)


shape (5,)


In [13]:
print("shape",arr3.shape)
print("size",arr3.size)

shape (2, 2, 2)
size 8


In [15]:
3.##array initialization method

3.0

In [16]:
# zeros array
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# one array
one_arr = np.ones((1,3))
print(one_arr)

[[1. 1. 1.]]


In [21]:
# full array

full_arr = np.full((3,2),2)
print(full_arr)

[[2 2]
 [2 2]
 [2 2]]


In [22]:
## identiti matrix[all element 0 except diagonal 1]

id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
##empty array

print(np.empty(2))

[-2.00000000e+000  6.93407089e-310]


In [25]:
##evenly space array

print(np.arange(1,3,1))

[1 2]


In [26]:
# specif number of space between a range
print(np.linspace(1,10,4))






      

[ 1.  4.  7. 10.]


In [28]:
a = np.array([1,3,5,7,9])
print(a)


[1 3 5 7 9]


In [30]:
print(a[0])

1


In [31]:
print(a[-1])


9


In [32]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [33]:
# slicing:
#array[start:stop:step]

In [34]:
print(a[0:2])

[1 3]


In [35]:
print(a[-1])

9


In [36]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [43]:
print(arr2[1][2])

6


In [44]:
print(arr2[:, 2])

[3 6]


In [45]:
print(arr2[:,1])

[2 5]


In [46]:
arr3 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
print(arr3[2][2])

9
